pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    repo: heretse/node-drone-demo
    secrets: [ docker_username, docker_password ]
    dry_run: false # remove this to publish
